controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
index:
    path: /
    controller: App\Controller\IndexController::Home

urlsave:
    path: /articles/save
show:
    path: /articles/show/{id}
newarticle:
    path: /articles/new
updatearticle:
    path: /articles/update/{id}