controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

index:
    path: /
    controller: App\Controller\IndexController::Home
articles_list:
    path: /articles
    controller: App\Controller\IndexController::Home
articles_save:
    path: /articles/save
    controller: App\Controller\IndexController::Save

articles_show:
    path: /articles/show/{id}
    controller: App\Controller\IndexController::Show

articles_new:
    path: /articles/new
    controller: App\Controller\IndexController::New

articles_update:
    path: /articles/update/{id}
    controller: App\Controller\IndexController::Update
